
import com.sun.scenario.effect.impl.sw.java.JSWBlend_SOFT_LIGHTPeer;
import java.awt.Color;
import java.util.ArrayList;
import javafx.print.PrintSides;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import jdk.nashorn.internal.objects.NativeError;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 50431
 */
public class Frame extends javax.swing.JFrame {

    static Persona Per = new Persona();
    static Gerente Ger = new Gerente();
    static Articulo Art = new Articulo();
    static Comic Com = new Comic();
    static Juego Jue = new Juego();
    static Figura Fig = new Figura();
    static Mensaje Men = new Mensaje();

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBG_Sexo = new javax.swing.ButtonGroup();
        Mensajess = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        Emisor = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        JTA_Mensaje = new javax.swing.JTextArea();
        JB_Enviar = new javax.swing.JButton();
        JCB_Receptor = new javax.swing.JComboBox<>();
        JCB_Emisor = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        JTable_Mensajes = new javax.swing.JTable();
        JB_Back6 = new javax.swing.JButton();
        JB_Exit6 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        Personal = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        TBPersonas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JBAgregarGerente = new javax.swing.JButton();
        JP_GContra = new javax.swing.JPasswordField();
        JT_GUsuario = new javax.swing.JTextField();
        JCB_GCargo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        JBAgregarPersonal = new javax.swing.JButton();
        JCB_POcupacion = new javax.swing.JComboBox<>();
        JFT_PHoraE = new javax.swing.JFormattedTextField();
        JF_PHoraS = new javax.swing.JFormattedTextField();
        JFT_PSueldo = new javax.swing.JFormattedTextField();
        JFT_PAntig = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JF_PID = new javax.swing.JFormattedTextField();
        JF_PEdad = new javax.swing.JFormattedTextField();
        JF_PAltura = new javax.swing.JFormattedTextField();
        JF_PPeso = new javax.swing.JFormattedTextField();
        JCB_PEstadoC = new javax.swing.JComboBox<>();
        JT_PNombre = new javax.swing.JTextField();
        JRB_PMasculino = new javax.swing.JRadioButton();
        JRB_PFemenino = new javax.swing.JRadioButton();
        JB_Back5 = new javax.swing.JButton();
        JB_Exit5 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        Articulos = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        JCB_JPais = new javax.swing.JComboBox<>();
        JFT_JEdicion = new javax.swing.JFormattedTextField();
        JCB_JCasa = new javax.swing.JComboBox<>();
        JCB_JIngreso = new javax.swing.JComboBox<>();
        JB_JAdd = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        JFT_CVolumen = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        JT_CDesc = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        JS_CEstado = new javax.swing.JSlider();
        JC_CAdd = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        JB_FAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_FInstrucciones = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        JT_FDesc = new javax.swing.JTextArea();
        JFT_FGarantia = new javax.swing.JFormattedTextField();
        JCB_FIngreso = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        JB_AColor = new javax.swing.JButton();
        JT_AEditorial = new javax.swing.JTextField();
        JT_ATitulo = new javax.swing.JTextField();
        JFT_ATamano = new javax.swing.JFormattedTextField();
        JCB_APuntuacion = new javax.swing.JComboBox<>();
        JB_Back4 = new javax.swing.JButton();
        JB_Exit4 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        Inventarios = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTree_Articulos = new javax.swing.JTree();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTree_Personal = new javax.swing.JTree();
        jLabel46 = new javax.swing.JLabel();
        Emisor3 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        JB_Back = new javax.swing.JButton();
        JB_Exit = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        JB_Back7 = new javax.swing.JButton();
        JB_Back8 = new javax.swing.JButton();
        JB_Back9 = new javax.swing.JButton();
        JB_Back10 = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();

        Mensajess.setUndecorated(true);
        Mensajess.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Courier New", 1, 56)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Mensajes");
        Mensajess.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 290, 80));

        jTabbedPane2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Emisor.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        Emisor.setForeground(new java.awt.Color(204, 204, 204));
        Emisor.setText("Emisor:");
        jPanel3.add(Emisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Receptor:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        JTA_Mensaje.setColumns(20);
        JTA_Mensaje.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JTA_Mensaje.setRows(5);
        jScrollPane6.setViewportView(JTA_Mensaje);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 710, 210));

        JB_Enviar.setBackground(new java.awt.Color(51, 153, 0));
        JB_Enviar.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Enviar.setForeground(new java.awt.Color(153, 153, 153));
        JB_Enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Send.png"))); // NOI18N
        JB_Enviar.setText("Enviar");
        JB_Enviar.setBorder(null);
        JB_Enviar.setBorderPainted(false);
        JB_Enviar.setContentAreaFilled(false);
        JB_Enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_EnviarMouseClicked(evt);
            }
        });
        jPanel3.add(JB_Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 368, 250, 60));

        JCB_Receptor.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jPanel3.add(JCB_Receptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 280, -1));

        JCB_Emisor.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jPanel3.add(JCB_Emisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 280, -1));

        jTabbedPane2.addTab("Enviar", jPanel3);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTable_Mensajes.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        JTable_Mensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emisor", "Receptor", "Contenido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(JTable_Mensajes);

        jPanel7.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 14, 760, 400));

        jTabbedPane2.addTab("Enviados", jPanel7);

        Mensajess.getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 800, 470));

        JB_Back6.setBackground(new java.awt.Color(51, 153, 0));
        JB_Back6.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Back6.setForeground(new java.awt.Color(153, 153, 153));
        JB_Back6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Back.png"))); // NOI18N
        JB_Back6.setBorder(null);
        JB_Back6.setBorderPainted(false);
        JB_Back6.setContentAreaFilled(false);
        JB_Back6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Back6ActionPerformed(evt);
            }
        });
        Mensajess.getContentPane().add(JB_Back6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        JB_Exit6.setBackground(new java.awt.Color(51, 153, 0));
        JB_Exit6.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Exit6.setForeground(new java.awt.Color(153, 153, 153));
        JB_Exit6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Exit.png"))); // NOI18N
        JB_Exit6.setBorder(null);
        JB_Exit6.setBorderPainted(false);
        JB_Exit6.setContentAreaFilled(false);
        JB_Exit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Exit6ActionPerformed(evt);
            }
        });
        Mensajess.getContentPane().add(JB_Exit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/geek_gamer.png"))); // NOI18N
        Mensajess.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Personal.setUndecorated(true);
        Personal.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Courier New", 1, 56)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Personal");
        Personal.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 280, 70));

        TBPersonas.setBackground(new java.awt.Color(102, 102, 102));
        TBPersonas.setForeground(new java.awt.Color(0, 0, 0));
        TBPersonas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Contraseña");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Cargo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, -1));

        JBAgregarGerente.setBackground(new java.awt.Color(60, 145, 16));
        JBAgregarGerente.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JBAgregarGerente.setForeground(new java.awt.Color(0, 0, 0));
        JBAgregarGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Save.png"))); // NOI18N
        JBAgregarGerente.setText("Guardar");
        JBAgregarGerente.setBorder(null);
        JBAgregarGerente.setBorderPainted(false);
        JBAgregarGerente.setContentAreaFilled(false);
        JBAgregarGerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBAgregarGerenteMouseClicked(evt);
            }
        });
        jPanel1.add(JBAgregarGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 179, -1));

        JP_GContra.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jPanel1.add(JP_GContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 80, -1));

        JT_GUsuario.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jPanel1.add(JT_GUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 100, -1));

        JCB_GCargo.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JCB_GCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sucursal", "Planta" }));
        jPanel1.add(JCB_GCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 160, -1));

        TBPersonas.addTab("Gerente", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Ocupacion");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Hora Entrada");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Hora Salida");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Antigüedad");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Sueldo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        JBAgregarPersonal.setBackground(new java.awt.Color(51, 153, 0));
        JBAgregarPersonal.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JBAgregarPersonal.setForeground(new java.awt.Color(0, 0, 0));
        JBAgregarPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Save.png"))); // NOI18N
        JBAgregarPersonal.setText("Guardar");
        JBAgregarPersonal.setBorder(null);
        JBAgregarPersonal.setBorderPainted(false);
        JBAgregarPersonal.setContentAreaFilled(false);
        JBAgregarPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBAgregarPersonalMouseClicked(evt);
            }
        });
        jPanel2.add(JBAgregarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 170, 60));

        JCB_POcupacion.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JCB_POcupacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caja", "Limpieza", "Seguridad", "Ventas" }));
        jPanel2.add(JCB_POcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 140, -1));

        try {
            JFT_PHoraE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFT_PHoraE.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jPanel2.add(JFT_PHoraE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 60, -1));

        try {
            JF_PHoraS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JF_PHoraS.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jPanel2.add(JF_PHoraS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 60, -1));

        try {
            JFT_PSueldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFT_PSueldo.setText("  ");
        JFT_PSueldo.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jPanel2.add(JFT_PSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 65, -1));

        try {
            JFT_PAntig.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFT_PAntig.setText("  ");
        JFT_PAntig.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jPanel2.add(JFT_PAntig, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 60, -1));

        TBPersonas.addTab("Personal", jPanel2);

        Personal.getContentPane().add(TBPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 610, 240));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Nombre");
        Personal.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 20));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Identificación");
        Personal.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Edad");
        Personal.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, 20));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Altura ");
        Personal.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 20));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Sexo");
        Personal.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, 20));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Peso");
        Personal.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 20));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Estado Civil");
        Personal.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, 20));

        try {
            JF_PID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JF_PID.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        Personal.getContentPane().add(JF_PID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 210, 30));

        try {
            JF_PEdad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JF_PEdad.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        Personal.getContentPane().add(JF_PEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 50, 30));

        try {
            JF_PAltura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JF_PAltura.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        Personal.getContentPane().add(JF_PAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, 30));

        try {
            JF_PPeso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JF_PPeso.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        Personal.getContentPane().add(JF_PPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, 30));

        JCB_PEstadoC.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JCB_PEstadoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero(a)", "Casado(a)", "Union Libre" }));
        Personal.getContentPane().add(JCB_PEstadoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        JT_PNombre.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        Personal.getContentPane().add(JT_PNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 150, 30));

        JBG_Sexo.add(JRB_PMasculino);
        JRB_PMasculino.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JRB_PMasculino.setForeground(new java.awt.Color(204, 204, 204));
        JRB_PMasculino.setText("Masculino");
        JRB_PMasculino.setBorder(null);
        JRB_PMasculino.setContentAreaFilled(false);
        Personal.getContentPane().add(JRB_PMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        JBG_Sexo.add(JRB_PFemenino);
        JRB_PFemenino.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JRB_PFemenino.setForeground(new java.awt.Color(204, 204, 204));
        JRB_PFemenino.setText("Femenino");
        JRB_PFemenino.setBorder(null);
        JRB_PFemenino.setContentAreaFilled(false);
        Personal.getContentPane().add(JRB_PFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        JB_Back5.setBackground(new java.awt.Color(51, 153, 0));
        JB_Back5.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Back5.setForeground(new java.awt.Color(153, 153, 153));
        JB_Back5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Back.png"))); // NOI18N
        JB_Back5.setBorder(null);
        JB_Back5.setBorderPainted(false);
        JB_Back5.setContentAreaFilled(false);
        JB_Back5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Back5ActionPerformed(evt);
            }
        });
        Personal.getContentPane().add(JB_Back5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        JB_Exit5.setBackground(new java.awt.Color(51, 153, 0));
        JB_Exit5.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Exit5.setForeground(new java.awt.Color(153, 153, 153));
        JB_Exit5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Exit.png"))); // NOI18N
        JB_Exit5.setBorder(null);
        JB_Exit5.setBorderPainted(false);
        JB_Exit5.setContentAreaFilled(false);
        JB_Exit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Exit5ActionPerformed(evt);
            }
        });
        Personal.getContentPane().add(JB_Exit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/geek_gamer.png"))); // NOI18N
        Personal.getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        Articulos.setUndecorated(true);
        Articulos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setText("Edición");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel31.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setText("Casa de Elaboracion");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel32.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setText("País");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel36.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("Igresado por:");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        JCB_JPais.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JCB_JPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Costa Rica", "El Salvador", "Guatemala", "Honduras", "Nicaragua" }));
        jPanel5.add(JCB_JPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        try {
            JFT_JEdicion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFT_JEdicion.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jPanel5.add(JFT_JEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 39, -1));

        JCB_JCasa.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JCB_JCasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EA Sports", "RockStar", "Rusty Lake" }));
        jPanel5.add(JCB_JCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 170, -1));

        JCB_JIngreso.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JCB_JIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel5.add(JCB_JIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 170, -1));

        JB_JAdd.setBackground(new java.awt.Color(0, 204, 0));
        JB_JAdd.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_JAdd.setForeground(new java.awt.Color(204, 204, 204));
        JB_JAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Save.png"))); // NOI18N
        JB_JAdd.setText("Guardar");
        JB_JAdd.setBorder(null);
        JB_JAdd.setBorderPainted(false);
        JB_JAdd.setContentAreaFilled(false);
        JB_JAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_JAddMouseClicked(evt);
            }
        });
        jPanel5.add(JB_JAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 220, 50));

        jTabbedPane1.addTab("Juego", jPanel5);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("Volumen");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 28, -1, -1));

        jLabel29.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("Desc.");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 97, -1, -1));

        jLabel27.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("Estado");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        try {
            JFT_CVolumen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFT_CVolumen.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jPanel4.add(JFT_CVolumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 26, 50, 40));

        JT_CDesc.setColumns(20);
        JT_CDesc.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        JT_CDesc.setRows(5);
        jScrollPane3.setViewportView(JT_CDesc);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 350, 100));

        jLabel25.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("0");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        jLabel38.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 204, 204));
        jLabel38.setText("100");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, -1, -1));

        JS_CEstado.setPaintTicks(true);
        JS_CEstado.setValue(0);
        jPanel4.add(JS_CEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 220, -1));

        JC_CAdd.setBackground(new java.awt.Color(51, 204, 0));
        JC_CAdd.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JC_CAdd.setForeground(new java.awt.Color(204, 204, 204));
        JC_CAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Save.png"))); // NOI18N
        JC_CAdd.setText("Guardar");
        JC_CAdd.setBorder(null);
        JC_CAdd.setBorderPainted(false);
        JC_CAdd.setContentAreaFilled(false);
        JC_CAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JC_CAddMouseClicked(evt);
            }
        });
        jPanel4.add(JC_CAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 230, 60));

        jTabbedPane1.addTab("Comic", jPanel4);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("Desc.");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel34.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("Ins.");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jLabel35.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("Igresado por:");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel37.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("Garantia");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        JB_FAdd.setBackground(new java.awt.Color(51, 204, 0));
        JB_FAdd.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_FAdd.setForeground(new java.awt.Color(204, 204, 204));
        JB_FAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Save.png"))); // NOI18N
        JB_FAdd.setText("Guardar");
        JB_FAdd.setBorder(null);
        JB_FAdd.setBorderPainted(false);
        JB_FAdd.setContentAreaFilled(false);
        JB_FAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_FAddMouseClicked(evt);
            }
        });
        jPanel6.add(JB_FAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 230, 60));

        JT_FInstrucciones.setColumns(20);
        JT_FInstrucciones.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        JT_FInstrucciones.setRows(5);
        jScrollPane1.setViewportView(JT_FInstrucciones);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 240, 100));

        JT_FDesc.setColumns(20);
        JT_FDesc.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        JT_FDesc.setRows(5);
        jScrollPane2.setViewportView(JT_FDesc);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 240, 90));

        try {
            JFT_FGarantia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFT_FGarantia.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JFT_FGarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFT_FGarantiaActionPerformed(evt);
            }
        });
        jPanel6.add(JFT_FGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 60, 30));

        JCB_FIngreso.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JCB_FIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel6.add(JCB_FIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 214, -1));

        jTabbedPane1.addTab("Figura", jPanel6);

        Articulos.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 880, -1));

        jLabel21.setFont(new java.awt.Font("Courier New", 1, 56)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Artículos");
        Articulos.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel22.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Titulo");
        Articulos.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel23.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Tamaño");
        Articulos.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel24.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Editorial");
        Articulos.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jLabel26.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Puntuación");
        Articulos.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        JB_AColor.setBackground(new java.awt.Color(102, 102, 102));
        JB_AColor.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        JB_AColor.setForeground(new java.awt.Color(255, 255, 255));
        JB_AColor.setText("Color");
        JB_AColor.setBorder(null);
        JB_AColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AColorMouseClicked(evt);
            }
        });
        Articulos.getContentPane().add(JB_AColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 300, 40));

        JT_AEditorial.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        Articulos.getContentPane().add(JT_AEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 150, 40));

        JT_ATitulo.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        Articulos.getContentPane().add(JT_ATitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 130, 40));

        try {
            JFT_ATamano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JFT_ATamano.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        Articulos.getContentPane().add(JFT_ATamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 60, 40));

        JCB_APuntuacion.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JCB_APuntuacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        Articulos.getContentPane().add(JCB_APuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, -1, 40));

        JB_Back4.setBackground(new java.awt.Color(51, 153, 0));
        JB_Back4.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Back4.setForeground(new java.awt.Color(153, 153, 153));
        JB_Back4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Back.png"))); // NOI18N
        JB_Back4.setBorder(null);
        JB_Back4.setBorderPainted(false);
        JB_Back4.setContentAreaFilled(false);
        JB_Back4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Back4ActionPerformed(evt);
            }
        });
        Articulos.getContentPane().add(JB_Back4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        JB_Exit4.setBackground(new java.awt.Color(51, 153, 0));
        JB_Exit4.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Exit4.setForeground(new java.awt.Color(153, 153, 153));
        JB_Exit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Exit.png"))); // NOI18N
        JB_Exit4.setBorder(null);
        JB_Exit4.setBorderPainted(false);
        JB_Exit4.setContentAreaFilled(false);
        JB_Exit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Exit4ActionPerformed(evt);
            }
        });
        Articulos.getContentPane().add(JB_Exit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/geek_gamer.png"))); // NOI18N
        Articulos.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Inventarios.setUndecorated(true);
        Inventarios.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTree_Articulos.setBackground(new java.awt.Color(51, 51, 51));
        JTree_Articulos.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        JTree_Articulos.setForeground(new java.awt.Color(204, 204, 204));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Articulos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Comics");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Juegos");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Figuras");
        treeNode1.add(treeNode2);
        JTree_Articulos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree_Articulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTree_ArticulosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(JTree_Articulos);

        Inventarios.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 330, -1));

        JTree_Personal.setBackground(new java.awt.Color(51, 51, 51));
        JTree_Personal.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        JTree_Personal.setForeground(new java.awt.Color(204, 204, 204));
        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personal");
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gerentes");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Personal");
        treeNode1.add(treeNode2);
        JTree_Personal.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree_Personal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTree_PersonalMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(JTree_Personal);

        Inventarios.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 330, -1));

        jLabel46.setFont(new java.awt.Font("Courier New", 1, 56)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 204, 204));
        jLabel46.setText("Inventario");
        Inventarios.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 350, 80));

        Emisor3.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        Emisor3.setForeground(new java.awt.Color(204, 204, 204));
        Emisor3.setText("Personal:");
        Inventarios.getContentPane().add(Emisor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel47.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(204, 204, 204));
        jLabel47.setText("Articulos:");
        Inventarios.getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        JB_Back.setBackground(new java.awt.Color(51, 153, 0));
        JB_Back.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Back.setForeground(new java.awt.Color(153, 153, 153));
        JB_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Back.png"))); // NOI18N
        JB_Back.setBorder(null);
        JB_Back.setBorderPainted(false);
        JB_Back.setContentAreaFilled(false);
        JB_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_BackActionPerformed(evt);
            }
        });
        Inventarios.getContentPane().add(JB_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        JB_Exit.setBackground(new java.awt.Color(51, 153, 0));
        JB_Exit.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Exit.setForeground(new java.awt.Color(153, 153, 153));
        JB_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Exit.png"))); // NOI18N
        JB_Exit.setBorder(null);
        JB_Exit.setBorderPainted(false);
        JB_Exit.setContentAreaFilled(false);
        JB_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ExitActionPerformed(evt);
            }
        });
        Inventarios.getContentPane().add(JB_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/geek_gamer.png"))); // NOI18N
        Inventarios.getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Delete.png"))); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Edit.png"))); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Delete.png"))); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Edit.png"))); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geeklandia");
        setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB_Back7.setBackground(new java.awt.Color(51, 153, 0));
        JB_Back7.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Back7.setForeground(new java.awt.Color(153, 153, 153));
        JB_Back7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/big New Person.png"))); // NOI18N
        JB_Back7.setBorder(null);
        JB_Back7.setBorderPainted(false);
        JB_Back7.setContentAreaFilled(false);
        JB_Back7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Back7ActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Back7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        JB_Back8.setBackground(new java.awt.Color(51, 153, 0));
        JB_Back8.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Back8.setForeground(new java.awt.Color(153, 153, 153));
        JB_Back8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Big Add.png"))); // NOI18N
        JB_Back8.setBorder(null);
        JB_Back8.setBorderPainted(false);
        JB_Back8.setContentAreaFilled(false);
        JB_Back8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Back8ActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Back8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        JB_Back9.setBackground(new java.awt.Color(51, 153, 0));
        JB_Back9.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Back9.setForeground(new java.awt.Color(153, 153, 153));
        JB_Back9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Big Files.png"))); // NOI18N
        JB_Back9.setBorder(null);
        JB_Back9.setBorderPainted(false);
        JB_Back9.setContentAreaFilled(false);
        JB_Back9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Back9ActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Back9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        JB_Back10.setBackground(new java.awt.Color(51, 153, 0));
        JB_Back10.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        JB_Back10.setForeground(new java.awt.Color(153, 153, 153));
        JB_Back10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Big Message 2.png"))); // NOI18N
        JB_Back10.setBorder(null);
        JB_Back10.setBorderPainted(false);
        JB_Back10.setContentAreaFilled(false);
        JB_Back10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Back10ActionPerformed(evt);
            }
        });
        getContentPane().add(JB_Back10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, -1, -1));

        Titulo.setFont(new java.awt.Font("Courier New", 1, 122)); // NOI18N
        Titulo.setForeground(new java.awt.Color(204, 204, 204));
        Titulo.setText("Geeklandia");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        Titulo1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        Titulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/geek_gamer.png"))); // NOI18N
        getContentPane().add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_AColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AColorMouseClicked
        JB_AColor.setForeground(JColorChooser.showDialog(this, "Color del Articulo", Color.WHITE));
    }//GEN-LAST:event_JB_AColorMouseClicked

    private void JB_FAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_FAddMouseClicked
        try {
            Figura com = new Figura(JCB_FIngreso.getSelectedItem().toString(), JT_FDesc.getText(), JT_FInstrucciones.getText(), Integer.parseInt(JFT_FGarantia.getText()), JT_ATitulo.getText(), "Juego", JT_AEditorial.getText(), Integer.parseInt(JFT_ATamano.getText()), JCB_APuntuacion.getSelectedIndex() + 1, JB_AColor.getForeground());
            JOptionPane.showMessageDialog(this, "Figura agregado exitosamente.");
            DefaultTreeModel ModelTree = (DefaultTreeModel) JTree_Articulos.getModel();
            DefaultMutableTreeNode Raiz = (DefaultMutableTreeNode) ModelTree.getRoot();
            DefaultMutableTreeNode Node = new DefaultMutableTreeNode(com.toString());
            for (int i = 0; i < Raiz.getChildCount(); i++) {
                if (Raiz.getChildAt(i).toString().equals("Figuras")) {
                    DefaultMutableTreeNode Node2 = (DefaultMutableTreeNode) Raiz.getChildAt(i);
                    Node2.add(Node);
                }
            }
            ModelTree.reload();
            Object[] NewLine = {
                JT_ATitulo.getText(),
                JT_AEditorial.getText(),
                Integer.parseInt(JFT_ATamano.getText()),
                JCB_APuntuacion.getSelectedIndex() + 1,
                JB_AColor.getForeground(),
                Integer.parseInt(JFT_FGarantia.getText())};
            //Resets
            this.JT_FDesc.setText("");
            this.JT_FInstrucciones.setText("");
            this.JFT_FGarantia.setText("");
            this.JT_ATitulo.setText("");
            this.JT_AEditorial.setText("");
            this.JFT_ATamano.setText("");
            this.JCB_APuntuacion.setSelectedIndex(0);
            this.JB_AColor.setForeground(Color.WHITE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_JB_FAddMouseClicked

    private void JB_JAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_JAddMouseClicked
        try {
            Juego com = new Juego(JCB_JIngreso.getSelectedItem().toString(), Integer.parseInt(JFT_JEdicion.getText()), JCB_JCasa.getSelectedItem().toString(), JCB_JPais.getSelectedItem().toString(), JT_ATitulo.getText(), "Juego", JT_AEditorial.getText(), Integer.parseInt(JFT_ATamano.getText()), JCB_APuntuacion.getSelectedIndex() + 1, JB_AColor.getForeground());
            JOptionPane.showMessageDialog(this, "Juego agregado exitosamente.");
            //Agrega al Tree
            DefaultTreeModel ModelTree = (DefaultTreeModel) JTree_Articulos.getModel();
            DefaultMutableTreeNode Raiz = (DefaultMutableTreeNode) ModelTree.getRoot();
            DefaultMutableTreeNode Node = new DefaultMutableTreeNode(com.toString());
            for (int i = 0; i < Raiz.getChildCount(); i++) {
                if (Raiz.getChildAt(i).toString().equals("Juegos")) {
                    DefaultMutableTreeNode Node2 = (DefaultMutableTreeNode) Raiz.getChildAt(i);
                    Node2.add(Node);
                }
            }
            ModelTree.reload();
            //Resets
            this.JFT_JEdicion.setText("");
            this.JCB_JCasa.setSelectedIndex(0);
            this.JCB_JPais.setSelectedIndex(0);
            this.JT_ATitulo.setText("");
            this.JT_AEditorial.setText("");
            this.JFT_ATamano.setText("");
            this.JCB_APuntuacion.setSelectedIndex(0);
            this.JB_AColor.setForeground(Color.WHITE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_JB_JAddMouseClicked

    private void JC_CAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JC_CAddMouseClicked
        try {
            Comic com = new Comic(JT_CDesc.getText(), Integer.parseInt(JFT_CVolumen.getText()), JS_CEstado.getComponentCount(), JT_ATitulo.getText(), "Comic", JT_AEditorial.getText(), Integer.parseInt(JFT_ATamano.getText()), JCB_APuntuacion.getSelectedIndex() + 1, JB_AColor.getForeground());
            JOptionPane.showMessageDialog(this, "Comic agregado exitosamente");
            //Agrega al Tree
            DefaultTreeModel ModelTree = (DefaultTreeModel) JTree_Articulos.getModel();
            DefaultMutableTreeNode Raiz = (DefaultMutableTreeNode) ModelTree.getRoot();
            DefaultMutableTreeNode Node = new DefaultMutableTreeNode(com.toString());
            for (int i = 0; i < Raiz.getChildCount(); i++) {
                if (Raiz.getChildAt(i).toString().equals("Comics")) {
                    DefaultMutableTreeNode Node2 = (DefaultMutableTreeNode) Raiz.getChildAt(i);
                    Node2.add(Node);
                }
            }
            ModelTree.reload();
            //Resets
            this.JT_CDesc.setText("");
            this.JFT_CVolumen.setText("");
            this.JS_CEstado.setValue(0);
            this.JT_ATitulo.setText("");
            this.JT_AEditorial.setText("");
            this.JFT_ATamano.setText("");
            this.JCB_APuntuacion.setSelectedIndex(0);
            this.JB_AColor.setForeground(Color.WHITE);
        } catch (Exception e) {
            NativeError.printStackTrace(e);
        }
    }//GEN-LAST:event_JC_CAddMouseClicked

    private void JBAgregarPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBAgregarPersonalMouseClicked
        try {
            //Agregar al arraylist
            Personal com = new Personal(JCB_POcupacion.getSelectedItem().toString(),
                    Integer.parseInt(JFT_PHoraE.getText()),
                    Integer.parseInt(JF_PHoraS.getText()),
                    Integer.parseInt(JFT_PAntig.getText()),
                    Double.parseDouble(JFT_PSueldo.getText()),
                    JT_PNombre.getText(), ParaSexo(),
                    JCB_PEstadoC.getSelectedItem().toString(),
                    Integer.parseInt(JF_PID.getText()),
                    Integer.parseInt(JF_PEdad.getText()),
                    Double.parseDouble(JF_PPeso.getText()),
                    Double.parseDouble(JF_PAltura.getText()));
            //Anuncio para los puntos de los anuncios
            JOptionPane.showMessageDialog(this, "Personal de: " + JCB_POcupacion.getSelectedItem().toString() + ", agregado Exitosamente");
            //Combo Boxes necesarias
            DefaultComboBoxModel CBModel = (DefaultComboBoxModel) JCB_FIngreso.getModel();
            DefaultComboBoxModel CBModel2 = (DefaultComboBoxModel) JCB_JIngreso.getModel();
            DefaultComboBoxModel CBModel3 = (DefaultComboBoxModel) JCB_Emisor.getModel();
            DefaultComboBoxModel CBModel4 = (DefaultComboBoxModel) JCB_Receptor.getModel();
            CBModel.addElement(JT_PNombre.getText());
            CBModel2.addElement(JT_PNombre.getText());
            CBModel3.addElement(JT_PNombre.getText());
            CBModel4.addElement(JT_PNombre.getText());
            //Agrega al Tree
            DefaultTreeModel ModelTree = (DefaultTreeModel) JTree_Personal.getModel();
            DefaultMutableTreeNode Raiz = (DefaultMutableTreeNode) ModelTree.getRoot();
            DefaultMutableTreeNode Node = new DefaultMutableTreeNode(com.toString());
            for (int i = 0; i < Raiz.getChildCount(); i++) {
                if (Raiz.getChildAt(i).toString().equals("Personal")) {
                    DefaultMutableTreeNode Node2 = (DefaultMutableTreeNode) Raiz.getChildAt(i);
                    Node2.add(Node);
                }
            }
            ModelTree.reload();
            //Resets
            this.JCB_POcupacion.setSelectedIndex(0);
            this.JFT_PHoraE.setText("");
            this.JF_PHoraS.setText("");
            this.JFT_PAntig.setText("");
            this.JFT_PSueldo.setText("");
            this.JT_PNombre.setText("");
            this.JCB_PEstadoC.setSelectedIndex(0);
            this.JF_PID.setText("");
            this.JF_PEdad.setText("");
            this.JF_PPeso.setText("");
            this.JF_PAltura.setText("");
            this.JRB_PFemenino.setSelected(false);
            this.JRB_PMasculino.setSelected(false);
        } catch (Exception e) {
            //Por si acaso
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_JBAgregarPersonalMouseClicked

    private void JBAgregarGerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBAgregarGerenteMouseClicked
        try {
            //Agrega al arraylist
            Gerente com = (new Gerente(JT_GUsuario.getText(),
                    JP_GContra.getText(),
                    JCB_GCargo.getSelectedItem().toString(),
                    JT_PNombre.getText(), ParaSexo(),
                    JCB_PEstadoC.getSelectedItem().toString(),
                    Integer.parseInt(JF_PID.getText()),
                    Integer.parseInt(JF_PEdad.getText()),
                    Double.parseDouble(JF_PPeso.getText()),
                    Double.parseDouble(JF_PAltura.getText())));
            //Asegurando mi puntito por mensajes wapos
            JOptionPane.showMessageDialog(this, "Gerente de: " + JCB_GCargo.getSelectedItem().toString() + ", agregado Exitosamente");
            //Agrega a Combo Boxes necesarias
            DefaultComboBoxModel CBModel = (DefaultComboBoxModel) JCB_FIngreso.getModel();
            DefaultComboBoxModel CBModel2 = (DefaultComboBoxModel) JCB_JIngreso.getModel();
            DefaultComboBoxModel CBModel3 = (DefaultComboBoxModel) JCB_Emisor.getModel();
            DefaultComboBoxModel CBModel4 = (DefaultComboBoxModel) JCB_Receptor.getModel();
            CBModel.addElement(JT_PNombre.getText());
            CBModel2.addElement(JT_PNombre.getText());
            CBModel3.addElement(JT_PNombre.getText());
            CBModel4.addElement(JT_PNombre.getText());
            //Agrega a Tabla de Gerentes
            DefaultTreeModel ModelTree = (DefaultTreeModel) JTree_Personal.getModel();
            DefaultMutableTreeNode Raiz = (DefaultMutableTreeNode) ModelTree.getRoot();
            DefaultMutableTreeNode Node = new DefaultMutableTreeNode(com.toString());
            for (int i = 0; i < Raiz.getChildCount(); i++) {
                if (Raiz.getChildAt(i).toString().equals("Gerentes")) {
                    DefaultMutableTreeNode Node2 = (DefaultMutableTreeNode) Raiz.getChildAt(i);
                    Node2.add(Node);
                }
            }
            ModelTree.reload();
            //Reset de todos los swings 
            this.JT_GUsuario.setText("");
            this.JP_GContra.setText("");
            this.JCB_GCargo.setSelectedIndex(0);
            this.JT_PNombre.setText("");
            this.JCB_PEstadoC.setSelectedIndex(0);
            this.JF_PID.setText("");
            this.JF_PEdad.setText("");
            this.JF_PPeso.setText("");
            this.JF_PAltura.setText("");
            this.JRB_PFemenino.setSelected(false);
            this.JRB_PMasculino.setSelected(false);
        } catch (Exception e) {
            //Capturando exceptions
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_JBAgregarGerenteMouseClicked

    private void JB_EnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EnviarMouseClicked
        try {
            if (JCB_Emisor.getItemCount() <= 0) {
                JOptionPane.showMessageDialog(null, "Deben haber personas creadas");
            } else {
                try {
                    String in = JCB_Emisor.getSelectedItem().toString();
                    String on = JCB_Receptor.getSelectedItem().toString();
                    String st = JTA_Mensaje.getText();
                    Object[] row = {in, on, st};
                    DefaultTableModel modelo = (DefaultTableModel) JTable_Mensajes.getModel();
                    modelo.addRow(row);
                    JTable_Mensajes.setModel(modelo);
                    JOptionPane.showMessageDialog(null, "Enviado");
                    JTA_Mensaje.setText("");
                    JCB_Emisor.setSelectedIndex(0);
                    JCB_Receptor.setSelectedIndex(0);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error");
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error.");
        }
    }//GEN-LAST:event_JB_EnviarMouseClicked

    private void JB_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_BackActionPerformed
        this.setVisible(true);
        this.pack();
        this.setLocationRelativeTo(null);
        Inventarios.setVisible(false);
    }//GEN-LAST:event_JB_BackActionPerformed

    private void JB_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JB_ExitActionPerformed

    private void JB_Back4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Back4ActionPerformed
        this.setVisible(true);
        this.pack();
        this.setLocationRelativeTo(null);
        Articulos.setVisible(false);
    }//GEN-LAST:event_JB_Back4ActionPerformed

    private void JB_Exit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Exit4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JB_Exit4ActionPerformed

    private void JB_Back5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Back5ActionPerformed
        this.setVisible(true);
        this.pack();
        this.setLocationRelativeTo(null);
        Personal.setVisible(false);
    }//GEN-LAST:event_JB_Back5ActionPerformed

    private void JB_Exit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Exit5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JB_Exit5ActionPerformed

    private void JB_Back6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Back6ActionPerformed
        this.setVisible(true);
        this.pack();
        this.setLocationRelativeTo(null);
        Mensajess.setVisible(false);
    }//GEN-LAST:event_JB_Back6ActionPerformed

    private void JB_Exit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Exit6ActionPerformed
        System.exit(0);

    }//GEN-LAST:event_JB_Exit6ActionPerformed

    private void JB_Back7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Back7ActionPerformed
        this.setVisible(false);
        Personal.setVisible(true);
        Personal.pack();
        Personal.setLocationRelativeTo(null);
    }//GEN-LAST:event_JB_Back7ActionPerformed

    private void JB_Back8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Back8ActionPerformed
        this.setVisible(false);
        Articulos.setVisible(true);
        Articulos.pack();
        Articulos.setLocationRelativeTo(null);
    }//GEN-LAST:event_JB_Back8ActionPerformed

    private void JB_Back9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Back9ActionPerformed
        this.setVisible(false);
        Inventarios.setVisible(true);
        Inventarios.pack();
        Inventarios.setLocationRelativeTo(null);
    }//GEN-LAST:event_JB_Back9ActionPerformed

    private void JB_Back10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Back10ActionPerformed
        this.setVisible(false);
        Mensajess.setVisible(true);
        Mensajess.pack();
        Mensajess.setLocationRelativeTo(null);
    }//GEN-LAST:event_JB_Back10ActionPerformed

    DefaultMutableTreeNode Nodo;
    Persona per;
    Articulo art;

    
    private void JTree_PersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTree_PersonalMouseClicked
        
        //de verdad no se que pasa
        
        if (evt.isMetaDown()) {
            JOptionPane.showMessageDialog(null, "Mira el code porfa");
            int row = JTree_Personal.getClosestRowForLocation(evt.getX(), evt.getY());
            JTree_Personal.setSelectionRow(row);
            Object v1 = JTree_Personal.getSelectionPath().getLastPathComponent();
            Nodo = (DefaultMutableTreeNode) v1;

            if (Nodo.getUserObject() instanceof Persona) {
                per = (Persona) Nodo.getUserObject();
                jPopupMenu1.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            } else if (Nodo.getUserObject() instanceof Personal) {
                per = (Personal) Nodo.getUserObject();
                jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_JTree_PersonalMouseClicked

    private void JFT_FGarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFT_FGarantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFT_FGarantiaActionPerformed

    private void JTree_ArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTree_ArticulosMouseClicked
        
        //de verdad no se que pasa
        
        if (evt.isMetaDown()) {
            JOptionPane.showMessageDialog(null, "Mira el code porfa");
            int row = JTree_Articulos.getClosestRowForLocation(evt.getX(), evt.getY());
            JTree_Articulos.setSelectionRow(row);
            Object v1 = JTree_Articulos.getSelectionPath().getLastPathComponent();
            Nodo = (DefaultMutableTreeNode) v1;

            if (Nodo.getUserObject() instanceof Articulo) {
                art = (Articulo) Nodo.getUserObject();
                jPopupMenu2.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            } else if (Nodo.getUserObject() instanceof Personal) {
                art = (Articulo) Nodo.getUserObject();
                jPopupMenu2.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_JTree_ArticulosMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) JTree_Personal.getModel();
        per.setNombre(JOptionPane.showInputDialog("Nombre:"));
        m.reload();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) JTree_Personal.getModel();
        m.removeNodeFromParent(Nodo);
        m.reload(); //siempre hacer reload del modelo
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) JTree_Articulos.getModel();
        Art.setTitulo(JOptionPane.showInputDialog("Titulo:"));
        m.reload();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) JTree_Articulos.getModel();
        m.removeNodeFromParent(Nodo);
        m.reload();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    //Metodo para elegir el sexo
    private String ParaSexo() {
        String sexo = null;
        if (JRB_PMasculino.isSelected()) {
            sexo = "Masculino";
        } else if (JRB_PFemenino.isSelected()) {
            sexo = "Femenino";
        }
        return sexo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Articulos;
    private javax.swing.JLabel Emisor;
    private javax.swing.JLabel Emisor3;
    private javax.swing.JDialog Inventarios;
    private javax.swing.JButton JBAgregarGerente;
    private javax.swing.JButton JBAgregarPersonal;
    private javax.swing.ButtonGroup JBG_Sexo;
    private javax.swing.JButton JB_AColor;
    private javax.swing.JButton JB_Back;
    private javax.swing.JButton JB_Back10;
    private javax.swing.JButton JB_Back4;
    private javax.swing.JButton JB_Back5;
    private javax.swing.JButton JB_Back6;
    private javax.swing.JButton JB_Back7;
    private javax.swing.JButton JB_Back8;
    private javax.swing.JButton JB_Back9;
    private javax.swing.JButton JB_Enviar;
    private javax.swing.JButton JB_Exit;
    private javax.swing.JButton JB_Exit4;
    private javax.swing.JButton JB_Exit5;
    private javax.swing.JButton JB_Exit6;
    private javax.swing.JButton JB_FAdd;
    private javax.swing.JButton JB_JAdd;
    private javax.swing.JComboBox<String> JCB_APuntuacion;
    private javax.swing.JComboBox<String> JCB_Emisor;
    private javax.swing.JComboBox<String> JCB_FIngreso;
    private javax.swing.JComboBox<String> JCB_GCargo;
    private javax.swing.JComboBox<String> JCB_JCasa;
    private javax.swing.JComboBox<String> JCB_JIngreso;
    private javax.swing.JComboBox<String> JCB_JPais;
    private javax.swing.JComboBox<String> JCB_PEstadoC;
    private javax.swing.JComboBox<String> JCB_POcupacion;
    private javax.swing.JComboBox<String> JCB_Receptor;
    private javax.swing.JButton JC_CAdd;
    private javax.swing.JFormattedTextField JFT_ATamano;
    private javax.swing.JFormattedTextField JFT_CVolumen;
    private javax.swing.JFormattedTextField JFT_FGarantia;
    private javax.swing.JFormattedTextField JFT_JEdicion;
    private javax.swing.JFormattedTextField JFT_PAntig;
    private javax.swing.JFormattedTextField JFT_PHoraE;
    private javax.swing.JFormattedTextField JFT_PSueldo;
    private javax.swing.JFormattedTextField JF_PAltura;
    private javax.swing.JFormattedTextField JF_PEdad;
    private javax.swing.JFormattedTextField JF_PHoraS;
    private javax.swing.JFormattedTextField JF_PID;
    private javax.swing.JFormattedTextField JF_PPeso;
    private javax.swing.JPasswordField JP_GContra;
    private javax.swing.JRadioButton JRB_PFemenino;
    private javax.swing.JRadioButton JRB_PMasculino;
    private javax.swing.JSlider JS_CEstado;
    private javax.swing.JTextArea JTA_Mensaje;
    private javax.swing.JTextField JT_AEditorial;
    private javax.swing.JTextField JT_ATitulo;
    private javax.swing.JTextArea JT_CDesc;
    private javax.swing.JTextArea JT_FDesc;
    private javax.swing.JTextArea JT_FInstrucciones;
    private javax.swing.JTextField JT_GUsuario;
    private javax.swing.JTextField JT_PNombre;
    private javax.swing.JTable JTable_Mensajes;
    private javax.swing.JTree JTree_Articulos;
    private javax.swing.JTree JTree_Personal;
    private javax.swing.JDialog Mensajess;
    private javax.swing.JDialog Personal;
    private javax.swing.JTabbedPane TBPersonas;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
